CREATE SCHEMA IF NOT EXISTS governance;

CREATE TABLE IF NOT EXISTS governance.pipeline_runs (
    run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_name TEXT NOT NULL,
    status TEXT NOT NULL,
    git_commit TEXT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMPTZ,
    rows_processed BIGINT,
    duration_seconds DOUBLE PRECISION,
    error_message TEXT,
    CONSTRAINT pipeline_runs_status_check
        CHECK (status IN ('RUNNING', 'SUCCESS', 'FAILED'))
);

CREATE TABLE IF NOT EXISTS governance.data_quality_results (
    result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    check_name TEXT NOT NULL,
    dataset_name TEXT NOT NULL,
    check_type TEXT NOT NULL,
    status TEXT NOT NULL,
    expected_value TEXT,
    actual_value TEXT,
    severity TEXT,
    details JSONB,
    CONSTRAINT data_quality_results_pipeline_run_fk
        FOREIGN KEY (run_id)
        REFERENCES governance.pipeline_runs (run_id)
);
