CREATE SCHEMA IF NOT EXISTS governance;

CREATE TABLE IF NOT EXISTS governance.publication_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postgres_run_id BIGINT NOT NULL,
    governance_run_id TEXT NOT NULL,
    decision TEXT NOT NULL,
    quality_score INTEGER NOT NULL,
    pass_checks INTEGER NOT NULL,
    warn_checks INTEGER NOT NULL,
    fail_checks INTEGER NOT NULL,
    critical_failures INTEGER NOT NULL,
    privacy_failed_checks INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT publication_decisions_pipeline_run_fk
        FOREIGN KEY (postgres_run_id)
        REFERENCES governance.pipeline_runs (run_id),
    CONSTRAINT publication_decisions_decision_check
        CHECK (
            decision IN (
                'APPROVED',
                'APPROVED_WITH_WARNINGS',
                'BLOCKED'
            )
        ),
    CONSTRAINT publication_decisions_run_identity_key
        UNIQUE (postgres_run_id, governance_run_id)
);
